### ISSUE TITLE
Questions about a module you import

### ISSUE THREAD

**Issue by Milleupup** [chenyx09/belief-planning#4]
In Highway_env.py,you have a code "from HMM_backup_dyn import *" at the begining ,but i can't find any information about this package in the internet,can you tell what is it?and how can i install it?thanks!

**Comment by chenyx09** [comment]
I believe that is a file included in the repo.

**Comment by Milleupup** [comment]
您好，您的邮件我已收到，稍后会给您回复，谢谢！

**Comment by Milleupup** [comment]
but i can't find it in your repo,there isn't a file named "HMM_backup_dyn.py"

**Comment by chenyx09** [comment]
Sorry my bad, I just uploaded the file.

**Comment by Milleupup** [comment]
alright，thanks a lot!
